### ISSUE TITLE
Support for Netflix on Sony devices

### ISSUE THREAD

**Issue by fredrike** [alardus/portaller#21]
With my Sony Blu-ray player I'm not able to stream Netflix. This is the log from dnsmasq (from cold boot 'till access of the native Netflix app):

```
Mar 30 17:05:55 unknown daemon.info dnsmasq-dhcp[30412]: DHCPOFFER(br0) 192.168.1.34 3c:07:71:cd:3d:XX 
Mar 30 17:05:55 unknown daemon.info dnsmasq-dhcp[30412]: DHCPREQUEST(br0) 192.168.1.34 3c:07:71:cd:3d:XX 
Mar 30 17:05:55 unknown daemon.info dnsmasq-dhcp[30412]: DHCPACK(br0) 192.168.1.34 3c:07:71:cd:3d:XX 
Mar 30 17:05:55 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:55 unknown daemon.info dnsmasq[30412]: query[AAAA] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:55 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:56 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:56 unknown daemon.info dnsmasq[30412]: query[AAAA] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:56 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:57 unknown daemon.info dnsmasq[30412]: query[A] m.root-servers.net from 192.168.1.34
Mar 30 17:05:58 unknown daemon.info dnsmasq[30412]: query[A] ssm.internet.sony.tv from 192.168.1.34
Mar 30 17:05:58 unknown daemon.info dnsmasq[30412]: query[AAAA] ssm.internet.sony.tv from 192.168.1.34
Mar 30 17:05:58 unknown daemon.info dnsmasq[30412]: query[A] ssm.internet.sony.tv from 192.168.1.34
Mar 30 17:05:58 unknown daemon.info dnsmasq[30412]: query[A] blu-ray.update.sony.net from 192.168.1.34
Mar 30 17:05:58 unknown daemon.info dnsmasq[30412]: query[AAAA] blu-ray.update.sony.net from 192.168.1.34
Mar 30 17:05:58 unknown daemon.info dnsmasq[30412]: query[A] blu-ray.update.sony.net from 192.168.1.34
Mar 30 17:05:59 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:59 unknown daemon.info dnsmasq[30412]: query[AAAA] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:05:59 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:00 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:00 unknown daemon.info dnsmasq[30412]: query[AAAA] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:00 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:02 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:02 unknown daemon.info dnsmasq[30412]: query[AAAA] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:02 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:03 unknown daemon.info dnsmasq[30412]: query[A] call.me.sel.sony.com from 192.168.1.34
Mar 30 17:06:03 unknown daemon.info dnsmasq[30412]: query[AAAA] call.me.sel.sony.com from 192.168.1.34
Mar 30 17:06:03 unknown daemon.info dnsmasq[30412]: query[A] call.me.sel.sony.com from 192.168.1.34
Mar 30 17:06:36 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:36 unknown daemon.info dnsmasq[30412]: query[AAAA] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:36 unknown daemon.info dnsmasq[30412]: query[A] ssm1.internet.sony.tv from 192.168.1.34
Mar 30 17:06:46 unknown daemon.info dnsmasq[30412]: query[A] uiboot.netflix.com from 192.168.1.34
Mar 30 17:06:46 unknown daemon.info dnsmasq[30412]: query[AAAA] uiboot.netflix.com from 192.168.1.34
Mar 30 17:06:49 unknown daemon.info dnsmasq[30412]: query[A] nrdp.nccp.netflix.com from 192.168.1.34
Mar 30 17:06:49 unknown daemon.info dnsmasq[30412]: query[AAAA] nrdp.nccp.netflix.com from 192.168.1.34
Mar 30 17:06:49 unknown daemon.info dnsmasq[30412]: query[A] nrdp.nccp.netflix.com from 192.168.1.34
```

**Comment by fredrike** [comment]
I guess adding support for `nrdp.nccp.netflix.com` would do the _trick_.

**Comment by alardus** [comment]
Just to clarify:
1. That trick with separate ports for sniproxy listeners was only at upstream and was not implemented at  server side. Now I turned it on and you can point your local IP's to it.
2. Last time when I checked that was no problem with nrdp.nccp host - client looking for uiboot, then secure, and the last - api-global. But no big deal, I enabled nrdp.nccp too, so we can try with it and without it again.

**Comment by fredrike** [comment]
Just to clarify, this does not work atm? What is needed to get it to work?

**Comment by kruftik** [comment]
Fredrik,

you have to set up a number of virtual ip-s at your home router as well as
port forwarding of requests to the ip-s to additional ports at portaller's
side. just for example of the whole process, you can watch 1st merged
pull-request.

2015-04-01 10:09 GMT+05:00 Fredrik Erlandsson <notifications@github.com>:

> Just to clarify, this does not work atm? What is needed to get it to work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alardus/portaller/issues/21#issuecomment-88351836>.
>



-- 
С уважением, Гадеев Дмитрий

тел. +7 (982) 604-50-08
ICQ# 6279867
skype:kruftik

**Comment by alardus** [comment]
Fredrik, you are right, this trick not work automatically. Apologize for the long story below :)

## Story
Portaller works on assumption that client pass URL of host that they want to get inside header of SSL packet - in this case I can handle request, pass it to correct URL and everything's works well. In most cases that assumption is right.

But some clients not support SNI extension of SSL and send requests without URL - like Sony player in your case. In this scenario sniproxy, which I use for proxing, can't understand which host it must use and push 1st from default table. Client get wrong SSL certificate (because it can be from Pandora and not from Netflix) and generate an error.

To deal with this I need exactly know which host client is looking for and send it to IP which have only one SSL certificate - for requested host. This works well but requires set of public IP to associate them with uiboot.netflix.com and other hosts needed for Netflix (as example).

But I don't have pool of public IP, so all clients who can't use SNI extension are not supported - like PS3, Xbox 360 and some others, include yours Sony player.


## How to overcome limitations
Kruftik suggested to use Netfilter’s DNAT port forwarding mechanism to overcome this limitation. Using DNAT you can forward packets based on the source-ip:port to a remote-ip:port.

And here’s how this approach works: A DNS forwarder like Dnsmasq on your local Linux server will intercept domain names relevant for DNS unblocking. The intercepted domain names will be resolved to IP addresses which are routed to your Linux server within your LAN. Depending on the resolved IP addresses and ports, iptables DNAT rules will forward the request to a Portaller. Each domain name can have its own internal IP adress and thus its own listening port on your remote server’s HAProxy. And since every domain name can have it’s own listeners on Portaller, there’s no need for SNI.

For example: a DNS query to uiboot.netflix.com will not be resolved to its actual IP address 54.243.255.149, it will be resolved to 192.168.0.301 thanks to the internal DNS forwarder. The device asking for uiboot.netflix.com IP address will try to establish a HTTPS connection to 192.168.0.301:443 which is routed to  within your LAN. A DNAT rule will transparently forward all packets sent to 192.168.0.301:443 to 107.170.15.247:4432 which is the Portaller with special listener for this URL. Portaller listening on port 107.170.15.247:4432 will then forward all layer 4 traffic to uiboot.netflix.com:443.


## What exactly to do
* Set up additional local IP's on a router. For Netflix you need 3 of it, like 192.168.44.301, 192.168.44.302 and 192.168.44.303.

* Point your local dnsmmasq to this IP's, like
```
list address '/api-global.netflix.com/192.168.44.31'
list address '/uiboot.netflix.com/192.168.44.32'
list address '/secure.netflix.com/192.168.44.33'
```

* Configure iptables to forward requests from local IP to Portaller
```
iptables -t nat -I PREROUTING ! -i <your_external_interface> -p tcp -d 192.168.44.301 --dport 443 -j DNAT --to-destination 107.170.15.247:4431
iptables -t nat -I PREROUTING ! -i <your_external_interface> -p tcp -d 192.168.44.302 --dport 443 -j DNAT --to-destination 107.170.15.247:4432
iptables -t nat -I PREROUTING ! -i <your_external_interface> -p tcp -d 192.168.44.303 --dport 443 -j DNAT --to-destination 107.170.15.247:4433
iptables -t filter -I FORWARD ! -i <your_external_interface> -p tcp -d 107.170.15.247 --dport 4431 -j ACCEPT
iptables -t filter -I FORWARD ! -i <your_external_interface> -p tcp -d 107.170.15.247 --dport 4432 -j ACCEPT
iptables -t filter -I FORWARD ! -i <your_external_interface> -p tcp -d 107.170.15.247 --dport 4433 -j ACCEPT
```

Kruftik wrote a script to make this process more automatic: 
https://github.com/alardus/portaller/blob/master/netflix_redirect.sh

**Comment by fredrike** [comment]
Sorry for being a pita, but I would just map this for my TV, given it's IP, how can I modify this?

**Comment by alardus** [comment]
Would you please describe what device you are use as a router?

**Comment by fredrike** [comment]
I'm using a router running Tomato firmware (similar to dd-wrt). 

Did fool around with an extra virtual interface and running two dnsmasq but couldn't get it to work.

**Comment by alardus** [comment]
@kruftik would you please help @fredrike with dd-wrt settings? I have no experience with it.

**Comment by fredrike** [comment]
I finally spent some time on it..

I'm running @kruftik's script to generate configs for SNI (only modified the lan and wan interface part). And running an extra instance of dnsmasq as follows:

```
grep server /etc/dnsmasq.conf | dnsmasq -C -  -p 5353 \
  -A '/api-global.netflix.com/192.168.44.31' \
  -A '/uiboot.netflix.com/192.168.44.32' \
  -A '/secure.netflix.com/192.168.44.33' 

```
The grep is there to include other server commands from the dnsmasq.conf (it can probably be omitted). 

I also added the following `iptables` rules (`192.168.1.35`) is my Sony device I like to support:

```
iptables -t nat -A PREROUTING -s 192.168.1.35 -p tcp --dport 53 -j DNAT --to 192.168.1.1:5353
iptables -t nat -A PREROUTING -s 192.168.1.35 -p udp --dport 53 -j DNAT --to 192.168.1.1:5353
```
