### ISSUE TITLE
netflix app do not work on latest andorid/ios 

### ISSUE THREAD

**Issue by alardus** [alardus/portaller#32]

**Comment by alardus** [comment]
http://www.theverge.com/2016/1/6/10724112/netflix-global-expansion-russia-india

**Comment by kruftik** [comment]
Netflix in Russia is found to have very linited number of movies available.

However, this isn't the biggest fail. The one is the absence of House of
Cards. Many people seem to be ready to pay for Netflix only due to the
House as well as for other netflix original series :)
7 янв. 2016 г. 3:29 пользователь "Alexander Bykov" <notifications@github.com>
написал:

**Comment by alardus** [comment]
Yeah, got it :-/

**Comment by alardus** [comment]
Well, I have tested latest version of Netflix app for ios/android and both work well (yeah, House of Cards is available as well as Narcos ;) If you are still experiencing any troubles with them - let me know.
